LU decomposition (with partial pivoting)

1) factor PA = LU     O(n^3)

2) permute b -> Pb     free

3) solve Ly = Pb      O(n^2)

4) solve Ux = y       O(n^2)

In [1]:
from scipy.linalg import lu_factor, lu_solve
import numpy as np

In [2]:
A = [0]

In [3]:
LU, p = lu_factor(A)

ValueError: expected square matrix

In [4]:
b = np.array([1,1,1])

In [5]:
# solve a linear system using the LU factorization and then numpy

x = lu_solve((LU,p), b)
x

NameError: name 'LU' is not defined

In [6]:
x = np.linalg.solve(A,b)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

# A 'big' linear system

In [7]:
n = 1000
A = np.random.randn(n,n)
b = np.random.randn(n)

In [8]:
%%timeit

x = np.linalg.solve(A,b)

12 ms ± 377 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%%timeit
LU,p = lu_factor(A)
x = lu_solve((LU,p), b)

12.1 ms ± 172 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Solving linear systems with the same matrix, but multiple vectors b

In [10]:
m = 200

In [11]:
%%timeit
for i in range(m):
    b = np.random.randn(n)
    x = np.linalg.solve(A,b)

2.29 s ± 23.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%%timeit
LU,p = lu_factor(A) # this do be expensive
for i in range(m):
    b = np.random.randn(n)
    x = lu_solve((LU,p),b)

80.4 ms ± 9.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


The second one here is a lot faster!

# QR Factorization

A = { square or rectangular (tall and skinny)
    { the columns of A are independent
    
A (mxn) = Q x R  (mxn) x (nxn) where the following hold:

    1) columns of Q are orthonormal
    
    2) R is upper triangular and invertible.

# Full QR Factorization

A (mxn) = QxR (mxm)x(mxn)

In [13]:
from scipy.linalg import qr

In [14]:
# 5x4 example
A = np.random.randn(5,4)
A

array([[-1.1440796 , -1.47510236, -0.08318084, -0.4479228 ],
       [ 0.46245573, -0.1836277 ,  1.25293293, -0.21831149],
       [-0.91652798,  0.31886275, -0.85370334, -0.649568  ],
       [ 0.92678577, -2.08168784, -0.6736629 ,  0.36006773],
       [-2.10728815, -0.83914536, -1.62844887,  1.09297726]])

In [15]:
qr(A)

(array([[-0.41330796, -0.48656991,  0.53916147,  0.39866704, -0.37788326],
        [ 0.16706585, -0.09444396,  0.65422658, -0.14772898,  0.71647266],
        [-0.33110311,  0.17035402, -0.28148723,  0.72516333,  0.50621471],
        [ 0.33480882, -0.8289712 , -0.40101625,  0.05866617,  0.19092946],
        [-0.7612748 , -0.19523404, -0.20308473, -0.53845814,  0.22619412]]),
 array([[ 2.76810444,  0.41526996,  1.54051425, -0.34777054],
        [ 0.        ,  2.6788915 ,  0.65308534, -0.3839647 ],
        [ 0.        ,  0.        ,  1.61602357, -0.56784279],
        [ 0.        ,  0.        ,  0.        , -1.18476272],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]))

In [16]:
Q,R = qr(A,mode='economic')

In [17]:
Q

array([[-0.41330796, -0.48656991,  0.53916147,  0.39866704],
       [ 0.16706585, -0.09444396,  0.65422658, -0.14772898],
       [-0.33110311,  0.17035402, -0.28148723,  0.72516333],
       [ 0.33480882, -0.8289712 , -0.40101625,  0.05866617],
       [-0.7612748 , -0.19523404, -0.20308473, -0.53845814]])

In [18]:
R

array([[ 2.76810444,  0.41526996,  1.54051425, -0.34777054],
       [ 0.        ,  2.6788915 ,  0.65308534, -0.3839647 ],
       [ 0.        ,  0.        ,  1.61602357, -0.56784279],
       [ 0.        ,  0.        ,  0.        , -1.18476272]])

In [19]:
Q*R

ValueError: operands could not be broadcast together with shapes (5,4) (4,4) 

In [ ]:
Q@(Q.T)

In [ ]:
((Q.T)@Q).round(5)

In [ ]:
Q,R = qr(A,mode = 'full')

In [ ]:
Q.T.dot(Q).round(5)

In [ ]:
R

# September 24

## Two key properties of orthogonal matrices

1) If Q is orthogonal, then Q^T is orthogonal

2) If Q1, Q2 are orthogonal, then Q1* Q2 is orthogonal

### Goal: Give and idea for the Householder Algorithm

The key ingredient is reflectors: For every nonzero vector x, there is a reflector H such that:

    Hx = [* 0 0 ...... 0] ^T
    
Where H is an orthogonal matrix that looks like H = I - 2u * u ^ T

### Projections Onto Any Subspace
#### Here, the columnspace


QR Factorization:

A = QR (Economic QR fact.)

where Q has orthonormal columns , Q^T Q = I_n, and R is invertible.

projection matrix P is given by

 P = Q R(R^T Q^T Q R)^(-1) R^T Q^T
 
   = Q R (R^T R) ^(-1) R^T Q^T
   
   = QRR^(-1)(R^T)^(-1) R^T Q^T
   
   = QQ^T

#### Eigenvalue decomposition

A = S D S^(-1)

Where A is n, S is nxn and invertible, D is diagonal