# Machine Learning / Data Science Algorithms

Things we are gonna do:

**REGRESSION:** predict a continuous variable

Train a linear regression model

Make linear regression nonlinear (by adding polynomial features)

Overfitting and regularization

Kernel trick (black magic)

**Classification:** predict a discrete variable

Logistic Regression

Softmax regression

knn (k nearest neighbors) 

**Clustering:** Find groups of similar objects

k-means 

hierarchical clustering

Gaussian mixtures

**Recommender System:** predict user preference

We'll build a movie recommender

**Deep Learning:** for regression/classification

We'll build a neural network- from scratch !!

****

Grades based on:

Homework: 80%

Final Project: 20%  (He will send a list with ideas)

****

Tools we'll need:

Python

Python Libraries: numpy, matplotlib, pandas

Jupyter notebooks

### Useful Jupyter shortcuts

enter + shift: runs a cell

a: creates a cell above currently selected cell

b: creates a cell below currently selected cell

d+d: deletes currently selected cell

h: list of all keyboard shortcuts

Nested Itemized Lists:

- item 1
    - item 1.1
    - item 1.2
        - item 1.2.1
- item 2

Look up 'markdownguide.org' to see what you can do.

In [10]:
import numpy as np

In [1]:
2+2

4

In [2]:
a = 1
b = 0.5

a+b

1.5

In [3]:
print('hello world')

hello world


In [4]:
def my_boring_function(x):
    return x*x

In [5]:
my_boring_function(3)

9

In [11]:
my_boring_function(np.array([2,2]))

array([4, 4])

In [12]:
# create a vector from a list

v = np.array([1,2,3])
v

array([1, 2, 3])

In [13]:
v.shape

(3,)

In [18]:
v.flatten?

In [25]:
i = np.zeros(2)

In [20]:
i

array([1., 1.])

In [26]:
i[0].type

AttributeError: 'numpy.float64' object has no attribute 'type'